### ISSUE TITLE
Add Transformers4Rec to the list

### ISSUE THREAD

**Issue by rnyak** [huggingface/awesome-huggingface#17]
I want to add [Transformers4Rec](https://github.com/NVIDIA-Merlin/Transformers4Rec) a recently released open-source library to the list. The library works as a bridge between NLP and Recommender systems (RecSys) by integrating with HuggingFace Transformers, making state-of-the-art Transformer architectures available for RecSys researchers and industry practitioners. 

Transformers4Rec enables the usage of HF Transformers with any type of sequential tabular data. It is a flexible and efficient library for sequential and session-based recommendation available for both PyTorch and Tensorflow. 

@JetRunner I am not opening a PR yet because there is no category that can fit the repo-to-add. `Transformers4Rec` would fit under `Recommender Systems` category.

Additional resources:
- Library [repo](https://github.com/NVIDIA-Merlin/Transformers4Rec)
- [Documentation](https://nvidia-merlin.github.io/Transformers4Rec/main/index.html)
- [Blog Post](https://medium.com/nvidia-merlin/transformers4rec-4523cc7d8fa8)
- The [research paper](https://dl.acm.org/doi/10.1145/3460231.3474255) presented at the [RecSys'21](https://recsys.acm.org/recsys21/session-5/) conference.

**Comment by lewtun** [comment]
Closed by #18
